export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

// Assign a display name (helps with debugging and React DevTools)
RootLayout.displayName = 'RootLayout';

export default RootLayout;
